import {chromium} from '@playwright/test';import {createServer} from 'node:http';import {readFile} from 'node:fs/promises';import {resolve,extname} from 'node:path';
let requests=0,mode='success',body;
const server=createServer(async(req,res)=>{
 if(req.method==='POST'){requests++;let text='';for await(const chunk of req)text+=chunk;body=new URLSearchParams(text);await new Promise(r=>setTimeout(r,250));res.writeHead(mode==='success'?200:500);res.end();return;}
 try{const pathname=new URL(req.url,'http://localhost').pathname;const file=pathname==='/'?'/index.html':pathname==='/thanks'||pathname==='/thanks/'?'/thanks/index.html':pathname;res.setHeader('Content-Type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.png':'image/png'})[extname(file)]||'application/octet-stream');res.end(await readFile(resolve('dist','.'+file)));}catch{res.writeHead(404);res.end();}
});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const b=await chromium.launch();const p=await b.newPage({reducedMotion:'reduce'});const errors=[];p.on('pageerror',e=>errors.push(e.message));
try{
await p.goto(base);const button=p.locator('#application-form button');await button.click();if(requests||await p.locator('[aria-invalid=true]').count()!==3)throw Error('validation');await p.locator('#name').fill('テスト');await p.locator('#email').fill('wrong');await p.locator('#consent').check();await button.click();if(requests)throw Error('invalid email');await p.locator('#email').fill('test@example.com');await p.locator('#consent').uncheck();await button.click();if(requests)throw Error('consent');await p.locator('#consent').check();mode='failure';await button.click();await p.waitForFunction(()=>document.querySelector('#form-status').textContent.includes('送信に失敗'));if(new URL(p.url()).pathname==='/thanks'||await p.locator('#name').inputValue()!=='テスト'||await button.isDisabled())throw Error('failure handling');mode='success';await button.click();if(!await button.isDisabled())throw Error('busy');await p.locator('#application-form').evaluate(f=>f.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));await p.waitForURL(base+'/thanks');if(requests!==2||body.get('form-name')!=='career-consultation'||body.get('privacyConsent')!=='agreed'||body.get('message')!=='')throw Error('request changed');console.log('Validation, failure retention/no redirect, success redirect and no double-submit passed');
for(const width of [320,375,390,430,768,1024,1200,1440]){await p.setViewportSize({width,height:1000});await p.goto(base+'/thanks');await p.reload();await p.locator('.thanks-character').evaluate(i=>i.decode());if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth||[...document.querySelectorAll('h1,p,a')].some(e=>e.scrollWidth>e.clientWidth+2)))throw Error('layout '+width);if(width===390||width===1440)await p.screenshot({path:`screenshots/thanks-${width}.png`,fullPage:true});console.log(width+'px thanks image/reload/layout passed');}
await p.locator('.thanks-home').click();await p.waitForURL(base+'/');if(!await p.locator('#hero-heading').isVisible())throw Error('home');if(errors.length)throw Error(errors.join('\n'));console.log('Home link and zero JS errors passed');
}finally{await b.close();server.close();}
