import {chromium} from '@playwright/test';
import {writeFile} from 'node:fs/promises';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({reducedMotion:'reduce'});
const issues=[];page.on('pageerror',e=>issues.push(e.message));
const checks=[];
for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:900});const response=await page.goto('http://127.0.0.1:3000',{waitUntil:'networkidle'});if(!response.ok())throw new Error(`Page status: ${response.status()}`);await page.locator('h1').waitFor();if(issues.length)throw new Error(issues.join('\n'));await page.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=700){window.scrollTo(0,y);await new Promise(r=>setTimeout(r,30))}window.scrollTo(0,0)});await page.evaluate(()=>Promise.all(Array.from(document.images).filter(img=>img.complete).map(img=>img.decode().catch(()=>{}))));if(width===1440){await writeFile('screenshots/comparison/metrics.json',JSON.stringify(await page.evaluate(()=>({width:innerWidth,dpr:devicePixelRatio,zoom:visualViewport.scale,sections:Array.from(document.querySelectorAll('main section')).map(el=>({id:el.id,y:el.getBoundingClientRect().y+scrollY,height:el.getBoundingClientRect().height})),parts:Array.from(document.querySelectorAll('[data-comp-part]')).map(el=>({part:el.getAttribute('data-comp-part'),y:el.getBoundingClientRect().y+scrollY,height:el.getBoundingClientRect().height}))})),null,2));}await page.screenshot({path:`screenshots/lp-${width}.png`,fullPage:true});const size=await page.evaluate(()=>({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));if(size.scroll>size.client)throw new Error(`Horizontal overflow at ${width}: ${size.scroll}`);checks.push(`${width}px: no horizontal overflow`)}
await page.getByRole('button',{name:'入力内容を確認する'}).click();await page.getByText('お名前を入力してください。').waitFor();checks.push('Required validation works');
await page.getByLabel('お名前 必須').fill('確認 太郎');await page.getByRole('radio',{name:'メール',exact:true}).check();await page.getByLabel('連絡先・アカウント名 必須').fill('invalid');await page.getByRole('radio',{name:'収入を増やしたい'}).check();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'入力内容を確認する'}).click();await page.getByText('メールアドレスの形式を確認してください。').waitFor();checks.push('Email validation works');await page.getByLabel('連絡先・アカウント名 必須').fill('test@example.com');await page.getByRole('button',{name:'入力内容を確認する'}).click();await page.getByRole('status').filter({hasText:'申し込みは送信されていません'}).waitFor();checks.push('Unconnected form honestly reports not sent');
const faq=page.locator('.faqs summary').first();const wasOpen=await page.locator('.faqs details').first().evaluate(el=>el.open);await faq.focus();await page.keyboard.press('Enter');if(await page.locator('.faqs details').first().evaluate(el=>el.open)===wasOpen)throw new Error('FAQ keyboard failed');checks.push('FAQ keyboard toggle works');
await page.locator('#contact').scrollIntoViewIfNeeded();await page.waitForTimeout(350);if(!await page.locator('.mobile-cta').evaluate(el=>el.classList.contains('hide')))throw new Error('Mobile CTA visibility failed');checks.push('Mobile CTA hides at form');
await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:3000');await page.getByRole('button',{name:'メニューを開く'}).click();await page.getByRole('navigation',{name:'メインナビゲーション'}).getByRole('link',{name:'サポート',exact:true}).click();await page.waitForTimeout(200);checks.push('Mobile menu and anchors work');
if(issues.length)throw new Error(issues.join('\n'));await writeFile('screenshots/verification.txt',checks.join('\n')+'\nNo runtime errors.\n');console.log(checks.join('\n'));await browser.close();
