import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const code=readFileSync(new URL('./Code.gs',import.meta.url),'utf8');
function setup({storageFailure=false,sendFailure=false,quota=10,authFailure=false,replyTo='company@example.com',sentWriteFailure=false}={}){
 const rows=[],logs=[],emails=[],props={WEBHOOK_SECRET:'test-secret',SPREADSHEET_ID:'sheet-id',AUTO_REPLY_REPLY_TO:replyTo};let locked=false;
 const sheet={getLastRow:()=>rows.length+1,getRange:(row,col,n=1,m=1)=>({getDisplayValues:()=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>String(rows[row-2]?.[col+j-1]??''))),getDisplayValue:()=>String(rows[row-2]?.[col-1]??''),setValues:values=>{assert(locked);if(sentWriteFailure&&values[0][0]==='送信済み')throw Error('private-write');for(let i=0;i<n;i++)for(let j=0;j<m;j++)rows[row-2][col+j-1]=values[i][j]}}),appendRow:r=>{assert(locked);if(storageFailure)throw Error('private-data');rows.push(r)}};
 const context={console:{log:x=>logs.push(x)},ContentService:{MimeType:{TEXT:'text'},createTextOutput:text=>({text,setMimeType(){return this}})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k],deleteProperty:k=>delete props[k]})},LockService:{getScriptLock:()=>({tryLock(){assert(!locked);locked=true;return true},releaseLock(){locked=false}})},SpreadsheetApp:{openById:()=>({getSheetByName:()=>sheet}),flush:()=>assert(locked)},MailApp:{getRemainingDailyQuota(){if(authFailure)throw Error('private-auth');return quota},sendEmail(email){assert(locked);assert.equal(rows.at(-1)[10],'送信処理中');emails.push(email);if(sendFailure)throw Error('private-send');}}};vm.createContext(context);vm.runInContext(code,context);
 return {rows,logs,emails,props,context,post:(p,key='test-secret')=>context.doPost({parameter:{key},postData:{contents:JSON.stringify(p)}}).text,retry:()=>{props.AUTO_REPLY_RETRY_ID='receipt';context.retryAutoReply();}};
}
const p={id:'receipt',data:{name:'テスト',email:'test@example.com',message:'=HYPERLINK("https://example.com")'}};
test('save/send once, duplicate no email, exact subject and recipient',()=>{const s=setup();assert.equal(s.post(p),'OK');assert.equal(s.post(p),'Already registered');assert.equal(s.rows.length,1);assert.equal(s.rows[0].length,12);assert.equal(s.rows[0][5],'未対応');assert(s.rows[0][4].startsWith("'="));assert.equal(s.rows[0][10],'送信済み');assert(s.rows[0][11]);assert.equal(s.emails.length,1);assert.equal(s.emails[0].subject,'【Re】無料キャリア設計のお申し込みありがとうございます');assert.equal(s.emails[0].to,p.data.email);assert.equal(s.emails[0].replyTo,'company@example.com');assert.equal(s.emails[0].body,s.context.autoReplyBody_('テスト'));assert(s.emails[0].body.startsWith('テスト様\n\n'));s.retry();assert.equal(s.emails.length,1);});
test('auth/missing/storage errors keep original response contract',()=>{assert.equal(setup().post(p,'wrong'),'Unauthorized');assert.equal(setup().post({...p,id:''}),'Invalid data');const s=setup({storageFailure:true});assert.equal(s.post(p),'Error');assert(!s.logs.join('').includes('private-data'));assert.equal(s.emails.length,0);});
for(const [options,state] of [[{quota:0},'未送信（送信上限）'],[{authFailure:true},'未送信（権限・制限確認）'],[{replyTo:''},'未送信（設定不備）']])test(state+' preserves registration',()=>{const s=setup(options);assert.equal(s.post(p),'OK');assert.equal(s.rows.length,1);assert.equal(s.rows[0][10],state);assert.equal(s.emails.length,0);assert.equal(s.post(p),'Already registered');});
test('send exception: unknown, no automatic or manual blind retry',()=>{const s=setup({sendFailure:true});assert.equal(s.post(p),'OK');assert.equal(s.rows[0][10],'送信結果不明');s.post(p);s.retry();assert.equal(s.emails.length,1);assert(!s.logs.join('').includes('private-send'));});
test('send succeeded but state write failed: processing is never retried',()=>{const s=setup({sentWriteFailure:true});assert.equal(s.post(p),'OK');assert.equal(s.rows[0][10],'送信処理中');s.retry();assert.equal(s.emails.length,1);});
test('known-unsent config failure can be manually retried safely',()=>{const s=setup({replyTo:''});s.post(p);s.props.AUTO_REPLY_REPLY_TO='company@example.com';s.retry();s.retry();assert.equal(s.emails.length,1);assert.equal(s.rows[0][10],'送信済み');assert.equal(s.props.AUTO_REPLY_RETRY_ID,undefined);});
test('legacy blank status is not blindly resent',()=>{const s=setup();s.rows.push(['receipt',new Date(),'テスト','test@example.com','','未対応','','','','']);s.post(p);s.retry();assert.equal(s.emails.length,0);});
test('multiple email recipients rejected',()=>{const s=setup();assert.equal(s.post({...p,data:{...p.data,email:'a@example.com,b@example.com'}}),'Invalid data');assert.equal(s.emails.length,0);});
